language: python

python:
  - "3.7"

services:
  - docker

jobs:
  include:
    - stage: Test
      name: test
      script: bin/do.sh test
    - name: lint
      script: bin/do.sh lint
    - name: validate-build-install
      script: bin/do.sh validate-build-install

    - stage: "Build Image"
      name: build-image
      script: bin/do.sh build-image
